In [18]:
import pandas as pd

In [19]:
df=pd.read_csv(r"C:\MACHINE LEARNING PROJECTS\Navie Bayes Algorithsim Ham and Spam decection\spam_Emails_data.csv")
df

       label                                               text
0       Spam  viiiiiiagraaaa\nonly for the ones that want to...
1        Ham  got ice thought look az original message ice o...
2       Spam  yo ur wom an ne eds an escapenumber in ch ma n...
3       Spam  start increasing your odds of success & live s...
4        Ham  author jra date escapenumber escapenumber esca...
...      ...                                                ...
193847   Ham  on escapenumber escapenumber escapenumber rob ...
193848  Spam  we have everything you need escapelong cialesc...
193849   Ham  hi quick question say i have a date variable i...
193850  Spam  thank you for your loan request which we recie...
193851   Ham  this is an automatically generated delivery st...

[193852 rows x 2 columns]

In [20]:
df.isnull().sum()

label    0
text     2
dtype: int64

In [40]:
df.dropna(inplace=True)

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
encoder = LabelEncoder()

In [43]:
df['label']=encoder.fit_transform(df.label)

In [44]:
df

        label                                               text
0           1  viiiiiiagraaaa\nonly for the ones that want to...
1           0  got ice thought look az original message ice o...
2           1  yo ur wom an ne eds an escapenumber in ch ma n...
3           1  start increasing your odds of success & live s...
4           0  author jra date escapenumber escapenumber esca...
...       ...                                                ...
193847      0  on escapenumber escapenumber escapenumber rob ...
193848      1  we have everything you need escapelong cialesc...
193849      0  hi quick question say i have a date variable i...
193850      1  thank you for your loan request which we recie...
193851      0  this is an automatically generated delivery st...

[193850 rows x 2 columns]

In [45]:
x = df['text']

In [46]:
y = df['label']

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.25,random_state = 0)

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(stop_words='english')
X_train_vec = vector.fit_transform(x_train) 
X_test_vec = vector.transform(x_test)

In [52]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_vec, y_train)

MultinomialNB()

In [53]:
y_pred = model.predict(X_test_vec)

y_pred_prob = model.predict(X_test_vec)
y_pred_prob

array([1, 0, 0, ..., 0, 1, 0], shape=(48463,))

In [54]:
len(y_pred)

48463

In [55]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[25293   330]
 [ 1591 21249]]
0.9603615129067536

In [58]:
t ='luckyday lottery international international promotion prize award dept website www luckyday nl ref mli escapenumber ilgiescapenumber escapenumber batch ipd escapenumber escapenumber ptnl sir madam we are pleased to inform you of the result of the lottery winners international programs held on the escapenumberth of july escapenumber your e mail address attached to ticket number escapenumber escapenumber with serial number escapenumber escapenumber drew lucky numbers escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber which consequently won in the escapenumberrd category you have therefore been approved for a sum pay out of us escapenumber escapenumber six hundred and twenty three thousand united states dollars congratulations due to mix up of some numbers and names we ask that you keep your winning information very confidential till your claims has been processed and your prize money remitted to you this is part of our security proto col to avoid double claiming and unwarranted abuse of this program some by participants all participants were selected through a computer ballot system drawn from over escapenumber escapenumber escapenumber company and escapenumber escapenumber escapenumber individual email addresses and names from all over the world this promotional program takes place annually we hope with part of your winning you will take part in our next year usdescapenumber million international lottery to file for your claim please contact our your fiducial agent dr free de veen fortunegate agency tel escapenumber escapenumber escapenumber escapenumber fax escapenumber escapenumber escapenumber escapenumber e mail escapelong netscape net note that all winning must be claimed not later than escapenumberth of july escapenumber after this date all unclaimed funds will be included in the next stake please note in order to avoid unnecessary delays and complications please remember to quote your reference number and batch numbers in all correspondence furthermore should there be any change of address do inform our agent as soon as possible congratulations once more from our members of staff and thank you for being part of our promotional program note anybody under the age of escapenumber is automatically disqualified sincerely yours mrs helen van hal lottery coordinator reply email to luckyday winningawards nl or escapelong netscape net'
text1 = vector.transform([t])
prd = model.predict(text1)
original = encoder.inverse_transform(prd)
original[0]

np.int64(1)